# Initial legal categories extracted from apps/thai_wht/thai_wht/setup/install.py.
# Keep this app-owned copy so installations do not depend on the reference app.

INCOME_TYPES = (
	{
		"income_type_name": "1 เงินเดือนค่าจ้าง เบี้ยเลี้ยง",
		"pnd1": 1,
		"pnd2": 0,
		"pnd3": 0,
		"pnd53": 0,
		"pnd54": 0,
	},
	{
		"income_type_name": "2 ค่าธรรมเนียม ค่านายหน้า",
		"pnd1": 1,
		"pnd2": 0,
		"pnd3": 0,
		"pnd53": 0,
		"pnd54": 0,
	},
	{
		"income_type_name": "3 ค่าแห่งลิขสิทธิ์",
		"pnd1": 0,
		"pnd2": 1,
		"pnd3": 0,
		"pnd53": 1,
		"pnd54": 1,
	},
	{
		"income_type_name": "4 ก ดอกเบี้ย",
		"pnd1": 0,
		"pnd2": 1,
		"pnd3": 0,
		"pnd53": 1,
		"pnd54": 1,
	},
	{
		"income_type_name": "4 ข เงินปันผล",
		"pnd1": 0,
		"pnd2": 1,
		"pnd3": 0,
		"pnd53": 1,
		"pnd54": 1,
	},
	{
		"income_type_name": "4 อื่นๆ",
		"pnd1": 0,
		"pnd2": 1,
		"pnd3": 0,
		"pnd53": 1,
		"pnd54": 1,
	},
	{
		"income_type_name": "5 ค่าเช่า",
		"pnd1": 0,
		"pnd2": 0,
		"pnd3": 1,
		"pnd53": 1,
		"pnd54": 1,
	},
	{
		"income_type_name": "6 เงินได้จากวิชาชีพอิสระ",
		"pnd1": 0,
		"pnd2": 0,
		"pnd3": 1,
		"pnd53": 1,
		"pnd54": 1,
	},
	{
		"income_type_name": "7 การรับเหมาที่ผู้รับเหมาต้องลงทุนด้วยการจัดหาสัมภาระ",
		"pnd1": 0,
		"pnd2": 0,
		"pnd3": 1,
		"pnd53": 1,
		"pnd54": 0,
	},
	{
		"income_type_name": "8 อื่นๆ",
		"pnd1": 0,
		"pnd2": 0,
		"pnd3": 1,
		"pnd53": 1,
		"pnd54": 0,
	},
)
